---
# DB Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggdb-deploy
  namespace: bggns
  labels:
    app: bggdb
    name: bggdb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bggdb
      name: bggdb-pod
  template:
    metadata:
      labels:
        app: bggdb
        name: bggdb-pod
    spec:
      containers:
      - name: bggdb-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306

---
# DB Service
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns
  labels:
    app: bggdb
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bggdb
    name: bggdb-pod
  ports:
  - port: 3306
    targetPort: 3306