---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: minions
spec:
  accessModes:
  # Can fufill both
  - ReadWriteOnce
  # - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-retain
