# dont deploy yourself or smth cos it snot managed

# manages a group of ports
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: myns
  labels:
    app: dov
    name: dov-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      # must be a subset of labels
      app: myapp
      dept: htx
      commit: asdasd
  template:
    # automatically assumed to be a pod
    metadata:
      name: mypod
      namespace: myns
      labels:
        # any label can work
        # can search
        app: myapp
        dept: htx
        commit: asdasd
    spec:
      containers:
      # an array of containers, names must be unique
      - name: mypod-container
        image: chukmunnlee/dov-bear:v5
        # an alternative is
        # image: chukmunnlee/dov-bear@sha256:.......
        imagePullPolicy: IfNotPresent
        ports:  # container port
          - name: app-port
            containerPort: 3000
        env:
          - name: INSTANCE_NAME
            #value: my first pod
            #valueFrom config maps, secrets, fieldref
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: INSTANCE_HASH
            #value: abc123
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['pod-template-hash']

---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: myns
  labels:
    app: dov
    dept: htx
    commit: asded2123
spec:
  # Exists only within the cluster
  type: ClusterIP
  selector:
    # can search
    app: myapp
    dept: htx
    commit: asdasd
  ports:
  - port: 8000  # service port
    targetPort: app-port  # which port from the container